services:

  db:
    image: 'postgres:14-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=socialrides
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"

  client:
    image: 'dpage/pgadmin4'
    container_name: client
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=antonio@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=antonio
    depends_on:
      - db
    ports:
      - "2109:1998"